First section
paulotelles/landingvpn pull request #2
Opened 2021-01-22 15:19 UTC by paulotelles

- Criação dos componentes: _main, _title, _text, _button1, _container
- Alteração do _header com a inclusão da classe .overlay
- Alteração do js para interação com a nova classe .overlay
- Alteração do html com uma div para overlay no header, criação do main com a primeira section
- Adequação da primeira section do main para mobile

2021-01-22 18:04 UTC, vncsrbro requested changes

2021-01-22 18:04 UTC, vncsrbro commented on index.html
>      <header class="menu">
Também faltou adequar o espaço entre o menu e o hero, são 98px de distancia.

2021-01-22 18:12 UTC, vncsrbro commented on index.html
>      <header class="menu">
p.s: Tava debugando aqui e o logo ficou desalinhado por causa da div .overlay, mesmo ela sendo 0x0 o flex considera ela para aplicar o space-between. Como ela não é utilizada no desktop talvez seja interessante retirar ela do html e inserir pelo JS apenas quando clicar no icone do menu usando o `document.createElement()`

2021-01-22 20:15 UTC, paulotelles commented on index.html
>      <header class="menu">
corrigido. tinha dado aquele problema de colapsar as margens, já contornei com o padding.

2021-01-22 20:15 UTC, paulotelles commented on src/sass/components/_container.scss
> +    max-width: 50%;
corrigido

2021-01-22 20:15 UTC, paulotelles commented on src/sass/components/_container.scss
> +    display: flex;
Quando der eu queria falar com vc em ligação sobre isso, pois tenho alguns pontos e questionamentos sobre essa abordagem.

2021-01-22 20:15 UTC, paulotelles commented on src/sass/components/buttons/_button1.scss
> +  background-image: linear-gradient(
Fiz a correção, eu acabei me baseando no modelo e fiz como utilizado no modelo, que foi uma caixa com degrade. Mas a solução dessa maneira fica realmente melhor, acabei focando muito no modelo do que em retratar em sia. Já fiz a alteração.

2021-01-23 19:18 UTC, vncsrbro approved these changes

2021-01-24 16:27 UTC, merged