Section locations
paulotelles/landingvpn pull request #5
Opened 2021-01-27 19:58 UTC by paulotelles

Esse pull contempla:

- Section de Locations
- Section de testimonials
- Atualização dos arquivos do swiper, unifiquei todas as alterações do swiper em um único arquivo "_swiperModifier" e caso alguma ateração seja diferente dessa regra deve ser implementado junto as alterações daquela section em especifico.
- Adequação das duas section para mobile

2021-01-27 20:52 UTC, vncsrbro requested changes

2021-01-27 20:52 UTC, vncsrbro commented on index.html
> +        <div class="sponsored">
Em telas maiores que `960px` seus logos estão ultrapassando o tamanho do container.

<img width="1536" alt="Captura de Tela 2021-01-27 às 17 34 50" src="https://user-images.githubusercontent.com/30932300/106050540-1100fa80-60c6-11eb-808d-267b65cbe5a4.png">

E bora preencher esses `alt` vazios? 😆

2021-01-27 20:52 UTC, vncsrbro commented on index.html
> +          <img src="./src/img/amazon.png" alt="">
O logo da amazon estava mal formatado no layout, usa esse que tem menos espaço transparente como fundo:
![amazon](https://user-images.githubusercontent.com/30932300/106051035-a9977a80-60c6-11eb-90c6-8902e48777d2.png)

2021-01-27 20:52 UTC, vncsrbro commented on src/sass/components/_card2.scss
> +    padding: 6%;
Esse padding de 6% ta renderizando aproximadamente 20px no mobile (tela 375px) e no layout são `30px`
<img width="483" alt="Captura de Tela 2021-01-27 às 17 43 32" src="https://user-images.githubusercontent.com/30932300/106051476-435f2780-60c7-11eb-8e62-451b5eee66a6.png">

2021-01-27 20:52 UTC, vncsrbro commented on src/js/index.js
> +var swiperCard = new Swiper(".swiper-card2", {
Assim que eu carrego a página o slide permite que eu deslize para a direita sendo que não existe mais conteúdo, isso tem relação com o `centeredSlides`. E não esquece que o campo `initialSlide` inicia a contagem do index no `0`. 

Para telas maiores que 640 nós queremos sempre visualizar 3 slides por vez, deixa como `slidesPerView: "auto"` pode ser um problema.

2021-01-27 20:52 UTC, vncsrbro commented on src/sass/components/_swiperModifier.scss
> +    width: auto;
Eu não entendi muito bem a necessidade dessa classe já que o `width` dos slides é definido automaticamente pela biblioteca de acordo com os parametros que vc passa no js.

2021-01-27 21:48 UTC, paulotelles commented on src/sass/components/_card2.scss
> +    padding: 6%;
o problema é que no layout de 320px os 30px estoura, e o mínimo que consegui ficar de uma maneira boa nos dois foi de 6%, mas vou tentar aumentar um pouco para ver se da certo.

2021-01-27 21:55 UTC, paulotelles commented on src/js/index.js
> +var swiperCard = new Swiper(".swiper-card2", {
Então, o problema maior que eu tive foi com os layouts em tablet pois os mesmos estavam muito quebrados e tamanhos próximos ao do próximo breakpoint com apenas um estava ficando muito estranho. Com o Auto ele e o centeredSlides eu consigo manter um deles aparecendo e um "preview" de um pedaço dos outros, removendo esse problema. Depois quando tiver um tempo podemos discutir sobre essa parte?

2021-01-28 14:17 UTC, paulotelles commented on src/sass/components/_card2.scss
> +    padding: 6%;
solução discutida em reunião, vou manter os 6% pois o layout hj não contempla para telas 320px e esse ajuste foi necessário para cobrir esse tipo de tela.

2021-01-28 14:17 UTC, paulotelles commented on index.html
> +        <div class="sponsored">
preenchidos

2021-01-28 14:18 UTC, paulotelles commented on src/js/index.js
> +var swiperCard = new Swiper(".swiper-card2", {
corrigido conforme conversamos em reunião

2021-01-28 14:18 UTC, paulotelles commented on index.html
> +          <img src="./src/img/amazon.png" alt="">
corrigido

2021-01-28 14:19 UTC, merged